"""Constants for use with datetime."""

SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = 60
HOURS_IN_DAY = 24
DAYS_IN_WEEK = 7
DAYS_IN_YEAR = 365

HOURS_IN_WEEK = DAYS_IN_WEEK * HOURS_IN_DAY
HOURS_IN_YEAR = HOURS_IN_DAY * DAYS_IN_YEAR

SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY
SECONDS_IN_WEEK = SECONDS_IN_DAY * DAYS_IN_WEEK
SECONDS_IN_YEAR = DAYS_IN_YEAR * SECONDS_IN_DAY
